logs_root_path: logs_proto
object_id: "mug"
train:
- "2018-05-14-22-31-21" # 'the best coffee'
- "2018-05-14-22-33-14" # 'the best coffee'
# - "2018-05-14-22-35-08" # 'the best coffee'
# - "2018-05-15-00-57-24" # 'the best coffee'
# - "2018-05-15-01-01-59" # 'the best coffee'
# - "2018-05-15-00-59-42" # 'the best coffee'
test: []
evaluation_labeled_data_path: 
- "nowhereyet"
