logs_root_path: /home/ashek/code/data/pdc/logs_proto

single_object_scenes_config_files:
  # pretraining objects
  - 10_drill_scenes.yaml
  - caterpillar_upright.yaml
  - dramamine.yaml
  - gopro_box.yaml
  - headphones.yaml

  # novel objects
  - mugs_brown.yaml
  - mugs_best.yaml # should be "seen before"
  - shoe_brown_boot.yaml
  - mugs_red.yaml # should be "seen before"
  - shoe_gray_nike.yaml # maybe similar to brown boot?
  - shoe_green_nike.yaml # definitely seen if gray nike treated as novel
  - shoe_red_nike.yaml # definitely seen
  - mugs_dreamy.yaml # should be "seen before"

multi_object_scenes_config_files: []
